### ISSUE TITLE
results bar

### ISSUE THREAD

**Issue by publicsphere** [smrose/ps#10]
These may already have been fixed, but there are problems with https://labs.publicsphereproject.org/ps/PGHCI/results.php

The results bar isn't working yet (you probably know that); the colors should be light grey for neutral, light green for good, and bright green for excellent.

The users report is empty. 

The pattern comments report contain reports that there are 0 comments and it repeats it.  (And the new pattern I added isn't reported.

<img width="925" alt="Screenshot 2024-05-04 at 12 35 55 PM" src="https://github.com/smrose/ps/assets/6635482/e2e76df0-72c4-48df-ac2d-1fdcc880d4b2">

**Comment by smrose** [comment]
The issue here was that there was no team associated with the project, despite we created one that we had intended to assign. It's true that a superuser can enter votes, but only team members are counted/displayed in the user lists. I added the team to the project, and now users are shown. This isn't, I can see, ideal. One fix would be to disallow superusers to enter assessments on the basis of being superusers.

With regard to the bars, they weren't broken - there weren't any votes that weren't "good." I added a few "excellent" votes to prove that they were working.
