### ISSUE TITLE
Implement pattern addition and editing by members

### ISSUE THREAD

**Issue by smrose** [smrose/ps#9]
We wish to allow project participants to add patterns and edit the patterns they have entered.

In order to determine which patterns have been entered by a particular member, patterns will need to be attributed. That can be done by adding  an `owner` column to the `pattern` table. That would be a foreign key on `phpauth_users.id`.

**Comment by publicsphere** [comment]
Two things:
1. patterns on the greekgeeks site have authors — and the labs site should also have these. I assumed it did. On greengeeks we have entries for, I think, three authors. (which is pretty clunky). The multiple authors issue could be addressed by having a author-pattern links table.  If we don't have authors for patterns on the labs site, we should.
2. If we have a link to create pattern on main project page, we should say something like, "If you don't see a pattern listed in the assessment page, please enter it here."   // the reason I thought the add pattern function belonged at the bottom of the assessment page was because they would have already seen the patterns and would be less likely to duplicate an existing one. But I now see the wisdom of putting it on the main page — if they want to do is create a pattern why should they have to go to the assessment page!

**Comment by smrose** [comment]
What we have in the Pattern Sphere is the brand new `pattern.creator` column. That's an integer-valued column that is a foreign key on `phpauth_user.id`. The reason we added it is so that when users in a project create a new pattern, they and only they are authorized to manage that pattern - specifically, they can update or delete it. This ought not be a surprise - we talked about the need to add it in order to allow pattern management.

So - yes we have authors, but not broadly - the only patterns that have them are the ones that users create for a project. It's a single-valued field, and it isn't displayed anywhere. (Turning it into a multi-valued field using an auxiliary table would be simple enough.) We have the concept that assessments in a project are anonymous, and we have carried that anonymity forward to user-created patterns. 

As far as the placement is concerned, the link could certainly be present on the assessment page in addition to being on the main page if you think that's useful. The issue for me is that I worry that users will enter assessment data and then click on the link to manage patterns and lose the assessment data.

In any event, with regard to authors, it's only meaningful to use pattern authors if the authorship is displayed somewhere.

Regardless, this issue has been implemented, so I'm closing it. It would be appropriate to have pattern authors be a distinct issue.
